camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName:
  filter:
    create: All tasks

server:
  port: 6060


spring:
  application:
    name: MC-CAMUNDA-ENGINE
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camunda
    username: root
    password: administrator

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  jersey:
    application-path: engine-rest



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      hostname: localhost